Add Ansible trigger

diff --git a/.github/workflows/validate-and-plan.yml b/.github/workflows/validate-and-plan.yml
--- a/.github/workflows/validate-and-plan.yml
+++ b/.github/workflows/validate-and-plan.yml
@@ -68,7 +68,23 @@ jobs:
           TF_VAR_base_vm_name: ${{ fromJSON(env.manifest).builds[0].custom_data.vm_name }}
         run: |
           terraform init -upgrade
-          terraform plan -out='plan.tfplan'
+          
+          # Turn off "exit on error" to capture the detailed exit code
+          set +e
+          terraform plan -detailed-exitcode -out='plan.tfplan'
+          EXIT_CODE=$?
+          set -e
+          
+          # Save the code to a file
+          echo "$EXIT_CODE" > plan.exitcode
+          
+          # Fail build only if it's a real error (1)
+          if [ $EXIT_CODE -eq 1 ]; then
+            echo "❌ Terraform Plan failed with error."
+            exit 1
+          fi
+          
+          echo "✅ Plan generated with Exit Code: $EXIT_CODE"
 
       - name: Upload Terraform plan to MinIO
         uses: ./.github/actions/s3-cp
@@ -78,6 +94,15 @@ jobs:
           aws_endpoint_url: ${{ secrets.MINIO_ENDPOINT }}
           source: plan.tfplan
           destination: s3://${{ secrets.MINIO_BUCKET_NAME }}/pr-${{ github.event.pull_request.number }}.tfplan
+      
+      - name: Upload ExitCode to MinIO
+        uses: ./.github/actions/s3-cp
+        with:
+          aws_access_key_id: ${{ secrets.MINIO_ACCESS_KEY }}
+          aws_secret_access_key: ${{ secrets.MINIO_SECRET_KEY }}
+          aws_endpoint_url: ${{ secrets.MINIO_ENDPOINT }}
+          source: plan.exitcode
+          destination: s3://${{ secrets.MINIO_BUCKET_NAME }}/pr-${{ github.event.pull_request.number }}.exitcode
 
       - name: Upload Terraform plan artifact
         uses: actions/upload-artifact@v5
